name: 5g-rl-project
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - intel-openmp=2025.0.0=haa95532_1164
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libllvm20=20.1.8=h3aa9ab2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libzlib=1.3.1=h02ab6af_0
  - llvmlite=0.45.1=py311hd5b4e5d_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - numba=0.62.1=py311hdb4872a_0
  - numpy-base=2.3.3=py311hc851d2b_1
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py311haa95532_1
  - pip=25.2=pyhc872135_1
  - python=3.11.14=h981015d_0
  - re2=2024.07.02=h214f63a_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - werkzeug=3.1.3=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - ale-py==0.11.2
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - gymnasium==1.2.1
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==6.33.0
      - psutil==7.1.2
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rich==14.2.0
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.4.1
      - torch-directml==0.2.5.dev240914
      - torchvision==0.19.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
prefix: D:\miniconda3\envs\5g-rl-project
